[build-system]
requires = ["setuptools>=42", "wheel", "cmake>=3.16"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-*"
skip = "pp* *-musllinux*"
test-requires = ["pytest"]
test-command = "pytest -q {project}/tests/python"
